/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package WHO;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author nojus
 */
public class Calculator extends javax.swing.JFrame {
     private int randomint;

    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddApp = new javax.swing.JButton();
        RemApp = new javax.swing.JButton();
        CalcEnergy = new javax.swing.JButton();
        CalcSavings = new javax.swing.JButton();
        BackB = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        AppList = new javax.swing.JTable();
        Title = new javax.swing.JLabel();
        Tips = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddApp.setText("Add Appliance");
        AddApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAppActionPerformed(evt);
            }
        });
        getContentPane().add(AddApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, -1, -1));

        RemApp.setText("Remove Appliance");
        RemApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemAppActionPerformed(evt);
            }
        });
        getContentPane().add(RemApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 370, -1, -1));

        CalcEnergy.setText("Calculate Energy Consumption");
        CalcEnergy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcEnergyActionPerformed(evt);
            }
        });
        getContentPane().add(CalcEnergy, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, -1, -1));

        CalcSavings.setText("Calculate Potential Savings");
        CalcSavings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcSavingsActionPerformed(evt);
            }
        });
        getContentPane().add(CalcSavings, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 420, -1, -1));

        BackB.setText("Back");
        BackB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBActionPerformed(evt);
            }
        });
        getContentPane().add(BackB, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, -1, -1));

        AppList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Appliance", "Energy Consumption (kWh)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(AppList);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 310, 170));

        Title.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("Energy Calculator");
        getContentPane().add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, -1, -1));

        Tips.setText("Go To Tips");
        Tips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipsActionPerformed(evt);
            }
        });
        getContentPane().add(Tips, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 480, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkg.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAppActionPerformed
        // TODO add your handling code here:
    String appliance = JOptionPane.showInputDialog(this, "Enter an Appliance:");
    String consumptionStr = JOptionPane.showInputDialog(this, "Enter Energy Consumption in kWh:");

    try {
        int consumption = Integer.parseInt(consumptionStr);

        DefaultTableModel model = (DefaultTableModel) AppList.getModel();
        model.addRow(new Object[]{appliance, consumption});
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter a valid integer for Energy Consumption.", "Input Error", JOptionPane.ERROR_MESSAGE);
    }

        
    }//GEN-LAST:event_AddAppActionPerformed

    private void RemAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemAppActionPerformed
        // TODO add your handling code here:
        int selectedrow = AppList.getSelectedRow();
        if (selectedrow != -1){
       DefaultTableModel model = (DefaultTableModel) AppList.getModel();
       model.removeRow(selectedrow);
               }
       else { JOptionPane.showMessageDialog(this, "Please select an appliance remove it.", "Selection Error", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_RemAppActionPerformed

    private void BackBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBActionPerformed

        Calculator frm1 = new Calculator();
        Landing frm2 = new Landing();
        frm2.setVisible(true);
        frm1.setVisible(false);
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_BackBActionPerformed

    private void TipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipsActionPerformed

        Calculator frm1 = new Calculator();
        Tips frm2 = new Tips();
        frm2.setVisible(true);
        frm1.setVisible(false);
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_TipsActionPerformed

    private void CalcEnergyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcEnergyActionPerformed
        // TODO add your handling code here:
        CalcTotalEnergyConsumption();
    }//GEN-LAST:event_CalcEnergyActionPerformed

    
       
    private void RandomNumb(){
    int min = 5;
    int max = 40;
    
    randomint = (int)Math.floor(Math.random() * (max - min + 1) + min);
    }
    
    private void CalcSavingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcSavingsActionPerformed
    RandomNumb();
    DefaultTableModel model = (DefaultTableModel) AppList.getModel();
    int rowCount = model.getRowCount();

    int totalConsumption = 0;

    for (int i = 0; i < rowCount; i++) {
        int consumption = (int) model.getValueAt(i, 1);
        totalConsumption += consumption;
    }
    int totalSavings = totalConsumption - randomint;
    

    JOptionPane.showMessageDialog(this, "Total energy with savings: " + totalSavings + " kWh", "Total Consumption", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_CalcSavingsActionPerformed

    private void CalcTotalEnergyConsumption() {
    DefaultTableModel model = (DefaultTableModel) AppList.getModel();
    int rowCount = model.getRowCount();

    int totalConsumption = 0;

    for (int i = 0; i < rowCount; i++) {
        int consumption = (int) model.getValueAt(i, 1);
        totalConsumption += consumption;
    }

    JOptionPane.showMessageDialog(this, "Total Energy Consumption: " + totalConsumption + " kWh", "Total Consumption", JOptionPane.INFORMATION_MESSAGE);
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddApp;
    private javax.swing.JTable AppList;
    private javax.swing.JButton BackB;
    private javax.swing.JLabel Background;
    private javax.swing.JButton CalcEnergy;
    private javax.swing.JButton CalcSavings;
    private javax.swing.JButton RemApp;
    private javax.swing.JButton Tips;
    private javax.swing.JLabel Title;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
