/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package WHO;

import java.util.ArrayList;
import javax.swing.JOptionPane;


/**
 *
 * @author kdoma
 */
public class GiGUI extends javax.swing.JFrame {

    private ArrayList<Top> tops;

    /**
     * Creates new form GiGUI
     */
    public GiGUI() {
        initComponents();
        tops = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titlelbl = new javax.swing.JLabel();
        Namelbl = new javax.swing.JLabel();
        Incentivetf = new javax.swing.JTextField();
        Incentivelbl = new javax.swing.JLabel();
        Nametf = new javax.swing.JTextField();
        Desclbl = new javax.swing.JLabel();
        Desctf = new javax.swing.JTextField();
        ShowIncentivesbtn = new javax.swing.JButton();
        GoBackbtn = new javax.swing.JButton();
        AddIncentivebtn = new javax.swing.JButton();
        BackgroundPIC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titlelbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Titlelbl.setForeground(new java.awt.Color(255, 255, 255));
        Titlelbl.setText("Government Incentives");
        getContentPane().add(Titlelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        Namelbl.setForeground(new java.awt.Color(255, 255, 255));
        Namelbl.setText("Name:");
        getContentPane().add(Namelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, 20));

        Incentivetf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncentivetfActionPerformed(evt);
            }
        });
        getContentPane().add(Incentivetf, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 110, -1));

        Incentivelbl.setForeground(new java.awt.Color(255, 255, 255));
        Incentivelbl.setText("IncentiveID:");
        getContentPane().add(Incentivelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));
        getContentPane().add(Nametf, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 110, -1));

        Desclbl.setForeground(new java.awt.Color(255, 255, 255));
        Desclbl.setText("Description:");
        getContentPane().add(Desclbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));
        getContentPane().add(Desctf, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 110, -1));

        ShowIncentivesbtn.setText("Show Incentives");
        ShowIncentivesbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowIncentivesbtnActionPerformed(evt);
            }
        });
        getContentPane().add(ShowIncentivesbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, -1));

        GoBackbtn.setText("Go Back");
        GoBackbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackbtnActionPerformed(evt);
            }
        });
        getContentPane().add(GoBackbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, -1, -1));

        AddIncentivebtn.setText("Add Incentive");
        AddIncentivebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddIncentivebtnActionPerformed(evt);
            }
        });
        getContentPane().add(AddIncentivebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        BackgroundPIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkg.png"))); // NOI18N
        getContentPane().add(BackgroundPIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IncentivetfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncentivetfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IncentivetfActionPerformed

    private void GoBackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackbtnActionPerformed
        TopGUI tGUI = new TopGUI();
        tGUI.show();

        dispose();
    }//GEN-LAST:event_GoBackbtnActionPerformed

    private void AddIncentivebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddIncentivebtnActionPerformed
        // TODO add your handling code here:
        String incentiveId = Incentivetf.getText();
        String name = Nametf.getText();
        String description = Desctf.getText();

        Top top = new Top(incentiveId, name, description);
        tops.add(top);

        // Optionally, you can clear the text fields after adding the data
        Incentivetf.setText("");
        Nametf.setText("");
        Desctf.setText("");

    }//GEN-LAST:event_AddIncentivebtnActionPerformed

    private void ShowIncentivesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowIncentivesbtnActionPerformed
        // TODO add your handling code here:
        StringBuilder result = new StringBuilder();
        for (Top top : tops) {
            result.append("IncentiveID: ").append(top.getIncentiveId())
                    .append(", Name: ").append(top.getName())
                    .append(", Description: ").append(top.getDescription())
                    .append("\n");
        }

        JOptionPane.showMessageDialog(this, result.toString(), "Incentives List", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_ShowIncentivesbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddIncentivebtn;
    private javax.swing.JLabel BackgroundPIC;
    private javax.swing.JLabel Desclbl;
    private javax.swing.JTextField Desctf;
    private javax.swing.JButton GoBackbtn;
    private javax.swing.JLabel Incentivelbl;
    private javax.swing.JTextField Incentivetf;
    private javax.swing.JLabel Namelbl;
    private javax.swing.JTextField Nametf;
    private javax.swing.JButton ShowIncentivesbtn;
    private javax.swing.JLabel Titlelbl;
    // End of variables declaration//GEN-END:variables
}
