/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package WHO;



import WHO.TopGUI;
import javax.swing.JOptionPane;

public class SpGUI extends javax.swing.JFrame {

    /**
     * Creates new form SpGUI
     */
    public SpGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titlelbl = new javax.swing.JLabel();
        SubTitle1 = new javax.swing.JLabel();
        SubTitle2 = new javax.swing.JLabel();
        GoBackbtn = new javax.swing.JButton();
        Costbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        BackgroundPic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titlelbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Titlelbl.setForeground(new java.awt.Color(255, 255, 255));
        Titlelbl.setText("Solar Power Cost Calculator");
        getContentPane().add(Titlelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        SubTitle1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SubTitle1.setForeground(new java.awt.Color(255, 255, 255));
        SubTitle1.setText("Please pick a solar panel:");
        getContentPane().add(SubTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        SubTitle2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SubTitle2.setForeground(new java.awt.Color(255, 255, 255));
        SubTitle2.setText("Location:");
        getContentPane().add(SubTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        GoBackbtn.setText("Go Back");
        GoBackbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackbtnActionPerformed(evt);
            }
        });
        getContentPane().add(GoBackbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, -1, -1));

        Costbtn.setText("Cost of Solar Panel");
        Costbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Costbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Monocrystalline Solar Panel", " ", "Polycrystalline Solar Panel", " ", "Concentrated PV Cell Solar Panel", " ", "Thin-Film Silicon Solar Panel", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 200, -1));

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Roof Mounted", " ", "Ground Mounted" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, 60));

        BackgroundPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkg.png"))); // NOI18N
        getContentPane().add(BackgroundPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GoBackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackbtnActionPerformed
        TopGUI tGUI = new TopGUI();
        tGUI.show();

        dispose();
    }//GEN-LAST:event_GoBackbtnActionPerformed

    private void CostbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostbtnActionPerformed
        // TODO add your handling code here:
        String selectedPanel = jList1.getSelectedValue();

        double cost = 0;

        if (selectedPanel != null) {
            switch (selectedPanel) {
                case "Monocrystalline Solar Panel":
                    cost = 1000;
                    break;
                case "Polycrystalline Solar Panel":
                    cost = 1500;
                    break;
                case "Concentrated PV Cell Solar Panel":
                    cost = 1250;
                    break;
                case "Thin-Film Silicon Solar Panel":
                    cost = 800;
                    break;
                default:
                    break;
            }
        }

        String selectedLocation = jList2.getSelectedValue();

        if (selectedLocation != null) {
            switch (selectedLocation) {
                case "Roof Mounted":
                    cost *= 2;
                    break;
                case "Ground Mounted":
                    cost *= 3;
                    break;
                default:
                    break;
            }
        }

        JOptionPane.showMessageDialog(this, "The cost of the selected solar panel is: " + cost + "€", "Cost Calculation", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_CostbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SpGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundPic;
    private javax.swing.JButton Costbtn;
    private javax.swing.JButton GoBackbtn;
    private javax.swing.JLabel SubTitle1;
    private javax.swing.JLabel SubTitle2;
    private javax.swing.JLabel Titlelbl;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
