/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package WHO;

import WHO.GiGUI;

/**
 *
 * @author kdoma
 */
public class TopGUI extends javax.swing.JFrame {

    /**
     * Creates new form TopGUI
     */
    public TopGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        REPbtn = new javax.swing.JButton();
        GIbtn = new javax.swing.JButton();
        SLbtn = new javax.swing.JButton();
        Menu = new javax.swing.JButton();
        BackgroundPic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        REPbtn.setText("Renewable Energy Provider ");
        REPbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REPbtnActionPerformed(evt);
            }
        });
        getContentPane().add(REPbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        GIbtn.setText("Government Incentives");
        GIbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GIbtnActionPerformed(evt);
            }
        });
        getContentPane().add(GIbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, -1));

        SLbtn.setText("Solar Calculator");
        SLbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SLbtnActionPerformed(evt);
            }
        });
        getContentPane().add(SLbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, -1, -1));

        Menu.setText("Main Menu");
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });
        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, -1));

        BackgroundPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkg.png"))); // NOI18N
        getContentPane().add(BackgroundPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void REPbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REPbtnActionPerformed
        RepGUI rGUI = new RepGUI();
        rGUI.show();
        
        dispose();
        
    }//GEN-LAST:event_REPbtnActionPerformed

    private void SLbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SLbtnActionPerformed
        SpGUI sGUI = new SpGUI();
        sGUI.show();
        
        dispose();
    }//GEN-LAST:event_SLbtnActionPerformed

    private void GIbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GIbtnActionPerformed
        GiGUI gGUI = new GiGUI();
        gGUI.show();
        
        dispose();
    }//GEN-LAST:event_GIbtnActionPerformed

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed

         TopGUI frm1 = new TopGUI();
         Landing frm2 = new Landing();
         frm2.setVisible(true);
         frm1.setVisible(false);
         dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_MenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TopGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TopGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TopGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TopGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TopGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundPic;
    private javax.swing.JButton GIbtn;
    private javax.swing.JButton Menu;
    private javax.swing.JButton REPbtn;
    private javax.swing.JButton SLbtn;
    // End of variables declaration//GEN-END:variables
}
