/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package WHO;

/**
 *
 * @author nojus
 */
public class Landing extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Landing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        Page2 = new javax.swing.JButton();
        Page1 = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Welcome To Our Application!");
        getContentPane().add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 320, 40));

        Page2.setBackground(new java.awt.Color(153, 204, 255));
        Page2.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        Page2.setText("Click Me To Go To Page 2");
        Page2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Page2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Page2MouseClicked(evt);
            }
        });
        Page2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Page2ActionPerformed(evt);
            }
        });
        getContentPane().add(Page2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, -1, 20));

        Page1.setBackground(new java.awt.Color(153, 204, 255));
        Page1.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        Page1.setText("Click Me To Go To Page 1");
        Page1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Page1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Page1ActionPerformed(evt);
            }
        });
        getContentPane().add(Page1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, 20));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkg.png"))); // NOI18N
        Background.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 981, 404));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Page2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Page2ActionPerformed

        
        Landing frm1 = new Landing();
        TopGUI frm2 = new TopGUI();
        frm2.setVisible(true);
        frm1.setVisible(false);
        dispose();


        // TODO add your handling code here:
    }//GEN-LAST:event_Page2ActionPerformed

    private void Page1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Page1ActionPerformed

        Landing frm1 = new Landing();
        NoahSec frm2 = new NoahSec();
        frm2.setVisible(true);
        frm1.setVisible(false);
        dispose();
                

        // TODO add your handling code here:
    }//GEN-LAST:event_Page1ActionPerformed

    private void Page2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Page2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Page2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Landing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Landing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Landing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Landing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Landing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton Page1;
    private javax.swing.JButton Page2;
    private javax.swing.JLabel Title;
    // End of variables declaration//GEN-END:variables
}
